### ISSUE TITLE
InputItem输入框的边框怎么去除？

### ISSUE THREAD

**Issue by wupengfei-mango** [didi/mand-mobile#679]
请问InputItem输入框的边框怎么去除？CellItem单元格有单独的属性no-border可以去除，InputItem该如何去除呢？

**Comment by xxyan0205** [comment]
InputItem 是基于 FieldItem的，没有提供去除边框的设置。如果有必要可以手动覆盖
```css
.md-input-item .md-field-item-content:after {
  display: none;
}
```
