### ISSUE TITLE
Seletor 组件在未设置 html font-size 时 padding 不正常

### ISSUE THREAD

**Issue by shoyuf** [didi/mand-mobile#76]
> mand-mobile version/项目版本
1.2.1

> recurring links(CodeSandbox is recommended)/复现链接(尽量以CodeSandbox复现)
[https://codepen.io/shoyuf-the-vuer/pen/YLezKq](https://codepen.io/shoyuf-the-vuer/pen/YLezKq)

> recurring steps/复现步骤
使用postcss-px-to-viewport ,未使用rem相关插件，其他组件样式正常
```css
.md-radio .md-field .md-field-item {
    padding: 0.22rem 0.32rem;
}
```

Version 1.2.1 新增的 vw适配方案 对现有项目有什么影响？
